import type { NextPage } from 'next'
import Head from 'next/head'
import CallToActionBlue from '../components/CallToAction/CallToActionBlue';
import CallToActionGreen from '../components/CallToAction/CallToActionGreen';
import Contact from '../components/Contact/Contact';
import References from '../components/References/References';
import Services from '../components/Services/Services';
import Testimonials from '../components/Testimonials/Testimonials';

const Home: NextPage = () => {
  return (
    <div className='font-kodchasan'>
      <Head>
        <title>Your Cleaner - Cleaning services in South England</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className='absolute -right-24 lg:right-0 top-16 xl:top-0 -z-10 w-[350px] h-[400px] md:w-[500px] md:h-[600px] lg:w-[650px] lg:h-[700px]  xl:w-[750px] xl:h-[900px]'>
        <img src="/images/banners/home.png" alt='Your Cleaner - Professional Cleaning Services' className=' object-fill topBannerImg' />
      </div>


      <div className='flex flex-row items-center container mx-auto'>
        <div className='w-3/5 md:w-1/2 mt-32 lg:mt-64 px-2 md:px-0'>
          <h1 className='font-bold text-blue font-kodchasan text-xl lg:text-4xl mb-4'>Lorem ipsum dolor sit amet, consectetur.</h1>
          <p className='font-normal font-heebo text-grey'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br />Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>

      <div className='container mx-auto mt-44 z-50 px-2 md:px-0'>
        <h2 className='font-bold font-kodchasan text-2xl text-blue'>Our Services</h2>
        <Services />
      </div>

      <div className='relative'>
        <div className="bgElement"></div>
        <div className='container mx-auto mt-44 z-50 px-2 md:px-0'>
          <h2 className='font-bold font-kodchasan text-2xl text-blue'>Our Work</h2>
          <References />
        </div>
      </div>


      <CallToActionBlue />

      <div className='relative'>
        <div className="bgElement2"></div>
        <div className='container mx-auto z-50 px-2 md:px-0'>
          <h2 className='font-bold font-kodchasan text-2xl text-blue'>Testimonials</h2>
          <Testimonials />
        </div>
      </div>

      <CallToActionGreen />

      <div className="container mx-auto mb-8 px-2 md:px-0">
        <Contact />
      </div>
      
    </div>
  )
}

export default Home
